kind: Service
apiVersion: v1
metadata:
  name: idea-garden-service
spec:
  selector:
    app: idea-garden
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-garden-deployment
  labels:
    app: idea-garden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idea-garden
  template:
    metadata:
      labels:
        app: idea-garden
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: idea-garden
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
